name: "FAP build"
on: [push, pull_request]
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: "ufbt: Build for Release branch"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        id: build-app
        with:
          sdk-channel: release
      - name: Upload app artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: dist/flipperzero_fnaf.fap
      - name: Lint sources
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.3
        with:
          # skip SDK setup, we already did it in previous step
          skip-setup: true
          task: lint
