name: "FAP: Build Application"
on:
  push:
  pull_request:
  schedule:
    - cron: "1 1 * * *"
jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: release
            sdk-channel: release
          - name: Unleashed Release
            sdk-index-url: https://up.unleashedflip.com/directory.json
            sdk-channel: release
    
    name: 'ufbt: Build for ${{matrix.name}}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build-app
        with:
          sdk-channel: ${{matrix.sdk-channel}}
          sdk-index-url: ${{matrix.sdk-index-url}}
          app-dir: src/flippy_temp
      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flippy-temp-${{ github.event.repository.name }}-${{ steps.build-app.outputs.suffix }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}
